title: "RabanserD's Blog"
email: daniel@rabanser.tech
description: "This is not a finished site"
baseurl: ""
url: "https://www.rabanser.tech"
github_username:  RabanserD
linkedin_username: RabanserD
google_analytics: UA-118970389-1
disqus: 
  shortname: www-rabanser-tech
#paginate: 1
#paginate_path: "blog/page:num"
show_excerpts: true
excerpt_separator: "<!--excerpt-->"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
