title: "RabanserD's Blog"
email: daniel@rabanser.tech
description: "This is not a finished site"
baseurl: ""
url: "https://www.rabanser.tech"
github_username:  RabanserD
linkedin_username: RabanserD
disqus: 
  shortname: www-rabanser-tech

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
