title: "RabanserD's Blog"
email: daniel@rabanser.tech
description: "Daniel Rabanser's Tech Blog"
baseurl: ""
url: "https://www.rabanser.tech"
github_username:  RabanserD
linkedin_username: RabanserD
google_analytics: UA-118970389-1
disqus: 
  shortname: www-rabanser-tech

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
