title: "RabanserD's Blog"
email: daniel[at]rabanser.tech
description: "Daniel Rabanser's Tech Blog"
baseurl: ""
url: "https://www.rabanser.tech"
github_username:  RabanserD
linkedin_username: RabanserD
google_analytics: UA-118970389-1
disqus: 
  shortname: www-rabanser-tech
show_excerpts: true
excerpt_separator: "<!--excerpt-->"

# Build settings
markdown: kramdown
theme: minima
minima:
  date_format: "%Y-%m-%d %H:%M"
paginate: 3
paginate_path: "/page-:num/"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
