title: "RabanserD's Blog"
email: daniel@rabanser.tech
description: "This is not a finished site"
baseurl: ""
url: "https://www.rabanser.tech"
twitter_username: RabanserD
github_username:  RabanserD
disqus: www-rabanser-tech

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
